# Copyright 2019 Tetrate
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

executors:
  builder:
    docker:
      - image: circleci/golang:1.13.3

  e2e_vm_linux:
    machine:
      # See https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      # Ubuntu 16.04, docker 19.03.8, docker-compose 1.25.5
      image: ubuntu-1604:202004-01

jobs:
  lint:
    executor: builder
    environment:
      # Run garbage collection more aggresively to avoid getting OOMed during the lint phase.
      GOGC: "20"
      # Circle CI executor has many cores (> 30) but throttles CPU and RAM. If we don't limit
      # this to the number of allocated cores, the job is likely to get OOMed and killed.
      GOMAXPROCS: "2"
    steps:
      - checkout
      - run: make init
      - run: ./ci/install-lint
      - run: ./ci/lint
          
  test:
    executor: builder
    steps:
      - checkout
      - run: make init
      - run: ./ci/install-envoy
      - run: ./ci/test
      - run:
          name: "Measure test coverage (for now, on a subset of tests)"
          command: make coverage GO_COVERAGE_EXTRA_OPTS="-p 1"
      - store_artifacts:
          path: build/coverage
          destination: /coverage

  bin:
    executor: builder
    steps:
      - checkout
      - run: make init
      - run:
          name: "Build `getenvoy` and `e2e` binaries for use in e2e tests"
          command: make bin
      # share `getenvoy` and `e2e` binaries with the downstream jobs
      - persist_to_workspace:
          root: build
          paths:
            - bin

  e2e_linux:
    executor: e2e_vm_linux
    steps:
      - checkout
      # re-use `getenvoy` and `e2e` binaries built by the upstream job
      - attach_workspace:
          at: build
      - run:
          name: "Build language-specific Docker build images"
          command: make builders
      - run:
          name: "Run e2e tests using `getenvoy` and `e2e` binaries built by the upstream job"
          environment:
            # run e2e tests on a `getenvoy` binary built by the upstream job
            E2E_GETENVOY_BINARY: /home/circleci/project/build/bin/linux/amd64/getenvoy
          # run e2e tests using `e2e` binary built by the upstream job
          command: build/bin/linux/amd64/e2e -ginkgo.v

  release:
    executor: builder
    steps:
      - checkout
      - run: make init
      - setup_remote_docker
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
      - bin
      - e2e_linux:
          requires:
            - bin
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
